#!/bin/bash

mkdir out

PATHIN="$(pwd)/in"
PATHOUT="$(pwd)/out"
echo $PATHOUT

docker stop pijuan

docker run --rm \
           -p 8888:8787 \
           -d \
           --name pijuan \
           -e PASSWORD=pijuan \
           --mount type=bind,source=$PATHIN,destination=/home/rstudio//in \
           --mount type=bind,source=$PATHOUT,destination=/home/rstudio//out \
           pijuan

firefox localhost:8888